// <auto-generated />
using System;
using Kuari.TodoApp.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuari.TodoApp.Repository.Migrations
{
    [DbContext(typeof(TodoAppDbContext))]
    [Migration("20230304102138_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kuari.TodoApp.Core.Entities.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Angular 15 yeniliklerine bakılacak",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "Asp.Net Core 6.0 WebAPI with ANGULAR M.Y TreversallApp geliştirilecek",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3,
                            Content = "Asp.NET Core 6.0 WebAPI with Angular SbrWebApp geliştirilecek",
                            IsCompleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
